### ISSUE TITLE
Troubleshooting Guidance

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-openstack-hot#8]
Can you point me in the direction of any troubleshooting when things don't work? I have Mitaka going and launched the stack. It built both BIG-IP's, inserted the ssh keypair, changed passwords, then looks like it may have stopped.

I see a lot of separate log files are created, but not sure in which order I should start looking for the issue.

This is the only thing in /var/log/messages

[root@host-10-100-0-134:NO LICENSE:Standalone] log # cat messages 
Dec  6 18:58:06 localhost notice syslog-ng[1417]: syslog-ng starting up; version='3.8.1'
Dec  6 18:59:33 localhost notice audispd: No plugins found, exiting
Dec  6 18:59:36 host-10-100-0-134 notice syslog-ng[1417]: Configuration reload request received, reloading configuration;
Dec  6 19:00:04 host-10-100-0-134 warning kernel: :  196.640576] 
Dec  6 19:00:04 host-10-100-0-134 warning kernel: :  196.640618] 
Dec  6 19:00:04 host-10-100-0-134 warning kernel: :  196.640678] ********************************************************
Dec  6 19:00:04 host-10-100-0-134 warning kernel: :  196.640735] *                                                      *
Dec  6 19:00:04 host-10-100-0-134 warning kernel: :  196.640785] * random root password = 17IUuIAX2n      *
Dec  6 19:00:04 host-10-100-0-134 warning kernel: :  196.640835] * random admin password = 52lPH1i6E9    *
Dec  6 19:00:04 host-10-100-0-134 warning kernel: :  196.640893] *                                                      *
Dec  6 19:00:04 host-10-100-0-134 warning kernel: :  196.640950] ********************************************************
Dec  6 19:00:04 host-10-100-0-134 warning kernel: :  196.640981] 
Dec  6 19:00:04 host-10-100-0-134 warning kernel: :  196.641011] 
Dec  6 19:01:13 host-10-100-0-134 notice logrotate: ALERT exited abnormally with [1]
Dec  6 19:01:43 localhost notice syslog-ng[1417]: Configuration reload request received, reloading configuration;
Dec  6 19:03:50 host-10-100-0-134 notice syslog-ng[1417]: Configuration reload request received, reloading configuration;
Dec  6 19:10:49 host-10-100-0-134 notice logrotate: ALERT exited abnormally with [1]
Dec  6 19:14:31 host-10-100-0-134 notice syslog-ng[1417]: Configuration reload request received, reloading configuration;

from: onboard-network.log

2017-12-07T03:38:12.792Z debug: [scripts/network.js] list /tm/sys/available
2017-12-07T03:38:12.801Z verbose: [scripts/network.js] tryUntil error: Public URI path not registered. Please see /var/log/restjavad.0.log and /var/log/restnoded/restnoded.log for details. tries left:
2017-12-07T03:38:12.804Z debug: [scripts/network.js]  {"code":404,"message":"Public URI path not registered. Please see /var/log/restjavad.0.log and /var/log/restnoded/restnoded.log for details.","referer":"127.0.0.1","restOperationId":4052065,"errorStack":["com.f5.rest.common.RestWorkerUriNotFoundException: Public URI path not registered. Please see /var/log/restjavad.0.log and /var/log/restnoded/restnoded.log for details.","at com.f5.rest.workers.ForwarderPassThroughWorker.cloneAndForwardRequest(ForwarderPassThroughWorker.java:572)","at com.f5.rest.workers.ForwarderPassThroughWorker.access$000(ForwarderPassThroughWorker.java:44)","at com.f5.rest.workers.ForwarderPassThroughWorker$1.completed(ForwarderPassThroughWorker.java:314)","at com.f5.rest.workers.ForwarderPassThroughWorker$1.completed(ForwarderPassThroughWorker.java:311)","at com.f5.rest.workers.EvaluatePermissions.completeEvaluatePermission(EvaluatePermissions.java:150)","at com.f5.rest.workers.EvaluatePermissions.evaluatePermission(EvaluatePermissions.java:78)","at com.f5.rest.workers.ForwarderPassThroughWorker.onForward(ForwarderPassThroughWorker.java:342)","at com.f5.rest.workers.ForwarderPassThroughWorker.onGet(ForwarderPassThroughWorker.java:753)","at com.f5.rest.common.RestWorker.callDerivedRestMethod(RestWorker.java:1154)","at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1119)","at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1385)","at com.f5.rest.common.RestServer.access$000(RestServer.java:48)","at com.f5.rest.common.RestServer$1.run(RestServer.java:329)","at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)","at java.util.concurrent.FutureTask.run(FutureTask.java:262)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)","at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)","at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)","at java.lang.Thread.run(Thread.java:745)\n"],"kind":":resterrorresponse"}
2017-12-07T03:38:12.805Z verbose: [scripts/network.js] Max tries reached.
2017-12-07T03:38:12.806Z verbose: [scripts/network.js] tryUntil error: Public URI path not registered. Please see /var/log/restjavad.0.log and /var/log/restnoded/restnoded.log for details. tries left: 21
2017-12-07T03:38:12.809Z debug: [scripts/network.js]  {"code":404,"message":"Public URI path not registered. Please see /var/log/restjavad.0.log and /var/log/restnoded/restnoded.log for details.","referer":"127.0.0.1","restOperationId":4052065,"errorStack":["com.f5.rest.common.RestWorkerUriNotFoundException: Public URI path not registered. Please see /var/log/restjavad.0.log and /var/log/restnoded/restnoded.log for details.","at com.f5.rest.workers.ForwarderPassThroughWorker.cloneAndForwardRequest(ForwarderPassThroughWorker.java:572)","at com.f5.rest.workers.ForwarderPassThroughWorker.access$000(ForwarderPassThroughWorker.java:44)","at com.f5.rest.workers.ForwarderPassThroughWorker$1.completed(ForwarderPassThroughWorker.java:314)","at com.f5.rest.workers.ForwarderPassThroughWorker$1.completed(ForwarderPassThroughWorker.java:311)","at com.f5.rest.workers.EvaluatePermissions.completeEvaluatePermission(EvaluatePermissions.java:150)","at com.f5.rest.workers.EvaluatePermissions.evaluatePermission(EvaluatePermissions.java:78)","at com.f5.rest.workers.ForwarderPassThroughWorker.onForward(ForwarderPassThroughWorker.java:342)","at com.f5.rest.workers.ForwarderPassThroughWorker.onGet(ForwarderPassThroughWorker.java:753)","at com.f5.rest.common.RestWorker.callDerivedRestMethod(RestWorker.java:1154)","at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1119)","at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1385)","at com.f5.rest.common.RestServer.access$000(RestServer.java:48)","at com.f5.rest.common.RestServer$1.run(RestServer.java:329)","at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)","at java.util.concurrent.FutureTask.run(FutureTask.java:262)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)","at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)","at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)","at java.lang.Thread.run(Thread.java:745)\n"],"kind":":resterrorresponse"}

**Comment by kaustriaf5** [comment]
@thomsonjames , which template are you using?
Depending on the template, and which step the error occurred, you may have to look at a couple different log files:
/var/log/onboard.log
/var/log/onboard-network.log
/var/log/onboard-cluster.log 

Also, what does the stack status show? There could have been a signal sent that shows which command failed, and which log file to look at.

**Comment by thomsonjames** [comment]
I was using this one: f5_bigip_cluster_2_nic.yaml I'll run it again and get more details.

**Comment by fbchan** [comment]
The error looks like the nodejs script not executing properly. Any chances the cloudlib not downloaded or installed properly (npm) on the box? DNS working for the management network? I curl to github and did a redirection to download the cloudlib and install locally. Will spun mine up again (spun up successfully last week or two ago) and will share my template.

**Comment by fbchan** [comment]
I uploaded my template in here (and output of nova-list) and logs files. Its working for me. I just did a quick edit of the env file and spun it up without much considering other stuff. As my environment running non-floating IP environment, I remove the floating portions for the external network.

https://github.com/fbchan/f5-openstack-hot/tree/master/supported/templates/cluster/2nic

Please ignore the ssl error and the wait_notify (due to metadata)

**Comment by kaustriaf5** [comment]
@thomsonjames Are you still having issues?

**Comment by kaustriaf5** [comment]
@thomsonjames I am going to close this issue as I have not heard back. Please feel free to open a new one if you are still running into errors. Thanks!

**Comment by kaustriaf5** [comment]
Also please note that as of v3.1.0, log files are now under `/var/log/cloud/openstack`
